### ISSUE TITLE
Question in PetrV2_head

### ISSUE THREAD

**Issue by jianingwangind** [megvii-research/PETR#12]
https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/dense_heads/petrv2_head.py#L511

When i set batch_size_per_gpu > 2, an error will be thrown here regarding to the mismatched shape: tmp[..., 8:] with shape(bs, num_obj, 2) while mean_time_stamp with shape bs.

Also, could you please explain what you are trying to do here? 

Thanks a lot.

**Comment by yingfei1016** [comment]
During the training process, we will randomly select one frame as the historical frame in the interval of 3T-27T. In different iterations, if two different frames are selected as historical frames, it is unreasonable to regression the same speed. Therefore, we divide the predicted speed by the time interval between the historical frame and the current frame, so that the regression is related to the time interval.
