### ISSUE TITLE
Why no reported the config of using swin as backbone and train log of PETR?

### ISSUE THREAD

**Issue by DearFishi** [megvii-research/PETR#32]
![image](https://user-images.githubusercontent.com/89983913/182320043-f5f327d8-d624-4065-9b17-cc0d43ec57f6.png)
Hi, thanks for your excellent work! I'm interested in using swin as backbone, and I found the result in your paper is very good. But I cannot find any log or config. Thanks!

**Comment by yingfei1016** [comment]
Hi,
We use swin as backbone to compare with bevdet and the resolution is 768x2112 as same as bevdet. Since PETR is a transformer detectors, when using transformer-based backbone, the convergence will be slower, the model must trained with CBGS. So the training is very time-consuming, even on A100 GPUs.  If you want to use swin transformer, you can refer to [config](https://drive.google.com/file/d/1opjm3XIgOya8yxekjEMGtTcyFcm_NAER/view?usp=sharing) and [log](https://drive.google.com/file/d/1-2i5vCjYrsEl4Aw7P7Zy4fsIAIO8pBCO/view?usp=sharing). Note that, the LID is closed, the optimizer should be modified. 

Now we try the query denoise to accelerated convergence and convnext as backbone. We recommend convnext to train the model without extra dataset. Here is the  [config](https://drive.google.com/file/d/1T-1nG5aLS0H3PXavqc_HhdVThESvpd-6/view?usp=sharing) and [backbone](https://drive.google.com/file/d/13W9QBN6Ebu8fmBvrp3wHnMC3hBr362MC/view?usp=sharing). We have adjusted the drop path rate and weight_decay. Note that you should modify the "backbone" to "img_backbone" in LearningRateDecayOptimizerConstructor. If you want to test on testset, you can train on trainval set with cbgs.

**Comment by DianCh** [comment]
Hi! Thanks for providing details about the convnext backbone. It looks like `LearningRateDecayOptimizerConstructor` is not yet supported by mmcv==1.4.0, could you provide more information on versions of mmlab libraries (a snapshot of your environment for these experiments would be great)? 

Thank you very much!
