### ISSUE TITLE
How to generate mmdet3d_nuscenes_30f_infos_train.pkl ? 

### ISSUE THREAD

**Issue by kaixinbear** [megvii-research/PETR#4]

**Comment by SuperHenry2333** [comment]
I have the same question.

**Comment by 24werewolf** [comment]
have the same question.

**Comment by 24werewolf** [comment]
> I have the same question.
https://drive.google.com/drive/folders/1_C2yuh51ROF3UzId4L1itwGQVUeVUxU6

**Comment by 24werewolf** [comment]
> _No description provided._

https://drive.google.com/drive/folders/1_C2yuh51ROF3UzId4L1itwGQVUeVUxU6

**Comment by SuperHenry2333** [comment]
> > I have the same question.
> > https://drive.google.com/drive/folders/1_C2yuh51ROF3UzId4L1itwGQVUeVUxU6

Thank you very much!

**Comment by kaixinbear** [comment]
Any intention to release the code for generating these pkl file ? So it could be used on the custom dataset.Thank you.

**Comment by yingfei1016** [comment]
This pkl file is directly converted from some available pkl files, because data processing is very time-consuming. We will organize and integrate the code into data processing as soon as possible.  Here we temporarily provide partial code to help you understand this process .  We mainly align the ‘extrinsics’ and ‘lidar2img’ of previous frame with current frame. 
[transform_30framepkl.py](https://drive.google.com/file/d/1BfjGbX_rfxJErxYY3QaP-rvHOzrEtbnc/view?usp=sharing)

**Comment by kaixinbear** [comment]
Thanks for your quick reply! It's helpful!

**Comment by kaixinbear** [comment]
Sorry to bother again, how to generate the mmdet3d_key_nuscenes_12hz_infos_{}.pkl and nuscenes_12hz_infos_{}.pkl ? Where do they come from ?

**Comment by bronyayang** [comment]
It will be great if the authors can provide us mmdet3d_key_nuscenes_12hz_infos_{}.pkl and nuscenes_12hz_infos_{}.pkl! Thanks in advance!

**Comment by yingfei1016** [comment]
@kaixinbear @bronyayang @SuperHenry2333 @24werewolf 

Hi all，
We have organized the code to generate the temporal pkl in https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py! It doesn't need mmdet3d_key_nuscenes_12hz_infos_{}.pkl anymore.
