### ISSUE TITLE
About the config of Swin tiny

### ISSUE THREAD

**Issue by PhoneSix** [megvii-research/PETR#45]
Thank you for releasing the code! I tried the swin tiny define in BEVDet in PETRv2, with 800*320 resolution, getting 40.6 NDS and 29.6 mAP, which is kind of low. Could you kindly release the config of swin tiny? Lots of thanks!

**Comment by yingfei1016** [comment]
Hi，

I think this result is right. As we explained in https://github.com/megvii-research/PETR/issues/32 ，the model should use a large resolution and train with cbgs，which is time consuming. For experimental verification, it is best to use a large backbone（> swin base or convnext base）with a small resolution, so that a higher baseline can be obtained. In our practice, convnext-base can be trained on 2080ti less than 1 day at 800x320 resolution (without cbgs). You can refer to the config we provide in  https://github.com/megvii-research/PETR/issues/32 and modify the config to a small resolution.
