### ISSUE TITLE
About the relationship between depth information and positional encoding

### ISSUE THREAD

**Issue by G4614** [megvii-research/PETR#53]
I mentioned that you have claimed "We argue that the 3D PE should be driven by the 2D features since the image feature can provide some informative guidance (e.g., depth). " So is there some probabilities that some explicit depth-like supervision can be combined into the PETRv2 series, or have you achieved some experiment results like this? THX!

**Comment by yingfei1016** [comment]
Hi,
Yes, introduce the explicit depth-like supervision in a suitable way, the performance of PETR can be improved.

**Comment by G4614** [comment]
Thx, so in your opinion, is there some methods about how to combine the depth supervision and position encoding together, I'm glad to explore this topic

**Comment by yingfei1016** [comment]
Some methods have explored it, for example:
![image](https://user-images.githubusercontent.com/106943722/192254852-ed9d2ff2-6ce9-4655-910e-73a4aab0f63f.png)

It may have a lot to improve, because mATE has not been significantly improved. I don't know the details. I think you can add a depthnet like bevdepth to predict a depth value. Then the 3D PE can be generated from this point instead of uniformly sampled 3d coordinates. You can also try to generate PE with sincos function instead of MLP.
